force-app/main/default/objects/Case/fields/Found_Yoda__c.field-meta.xml
<CustomField>
    <fullName>Found_Yoda__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Found Yoda</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Successful__c.field-meta.xml
<CustomField>
    <fullName>Successful__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Escaneo exitoso</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SwaggerScanner__c/SwaggerScanner__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SwaggerScanner</label>
</CustomObject>

force-app/main/default/objects/SwaggerScanner__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <label>Pass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SwaggerScanner__c/fields/retries__c.field-meta.xml
<CustomField>
    <fullName>retries__c</fullName>
    <label>retries</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WSSearchPlanet.cls
public with sharing class WSSearchPlanet {

    private static final SwaggerScanner__c SERVICE_CONFIG = SwaggerScanner__c.getInstance();
    static String url = SERVICE_CONFIG.Url__c;
    static String type = SERVICE_CONFIG.Type__c;
    static String user = SERVICE_CONFIG.User__c;
    static String pass = SERVICE_CONFIG.Pass__c;
    static Integer count;
    static String acessCodeQ;
    static String caseIdQ;

    @AuraEnabled
    public static String searchPlanetCallOut(String acesscode, String caseId){
        System.debug(caseId);
        System.debug(acesscode);
        caseIdQ = caseId;
        acessCodeQ = acesscode;
        count  = Integer.valueOf(SERVICE_CONFIG.retries__c);
        RestWS ws = makeRequest(acessCodeQ);
        searchPlanet resp = (searchPlanet) ws.invoke(new searchPlanet());
        System.debug(resp);
        return resp.message;  
    }

    @Future(callout=true)
    public static void searchPlanetCallOutRetries(String acessCodeP, Integer countP, String caseIdP){
        count  = countP;
        acessCodeQ = acessCodeP;
        caseIdQ = caseIdP;
        System.debug('Contador:'+ count);
        System.debug('acessCodeP:'+ acessCodeQ);
        System.debug('caseIdQ:'+ caseIdQ);
        if(count >= 0){
            System.debug('Nueva llamada');
            RestWS ws = makeRequest(acessCodeQ);
            searchPlanet resp = (searchPlanet) ws.invoke(new searchPlanet());
            System.debug(resp);
        } 
    }

    public static RestWS makeRequest(String acessCode){
        List<WSParameter> headerParams = new List<WSParameter>();
        WSParameter accept = new WSParameter('accept','application/json', true);
        Blob headerValue = Blob.valueOf(user +':'+pass);
        WSParameter authorization = new WSParameter('authorization',type+' '+ EncodingUtil.base64Encode(headerValue), true);
        headerParams.add(accept);
        headerParams.add(authorization);
        RestWS ws = new RestWS(url+acesscode,'GET',null,'',headerParams);
        return ws;
    }

    public class searchPlanet extends WSResult{
        public override void processResponse(HttpResponse response) {
            Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            message = String.valueOf(m.get('found'));
            Case caseToUpdate = [SELECT id, Status, Found_Yoda__c, Successful__c FROM Case WHERE Id = :caseIdQ];
            System.debug(caseToUpdate);
            caseToUpdate.Status = 'Closed';
            caseToUpdate.Successful__c = true;
            caseToUpdate.Found_Yoda__c = (Boolean)m.get('found');
            Database.SaveResult saveResultList = Database.update(caseToUpdate);
            if(saveResultList.isSuccess()) {
                System.debug('Se actualizo con exito');
            }
             else {
                for(Database.Error err : saveResultList.getErrors()) {
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug(err.getFields()); 
                }
            }
            
        }
 
		public override void processErrorResponse(HttpResponse response) {
            Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            message = String.valueOf(m.get('error'));
            System.debug('Encolar '+count);
            ID jobID = System.enqueueJob(new scheduleSearchPlanet(acessCodeQ,count,caseIdQ));   
		}
    }
}